sudo: required

services:
  - docker

language: go

go:
  - 1.x

addons:
  apt:
    packages:
      - libdb-dev

before_script:
  - go get github.com/golang/dep/cmd/dep

script:
  - make
  - make test
  - make -C docker
  - make -C docker build
